# sudo is required here since you must have elevated privileges to create the services during testing
sudo: required
language: python
python:
  - "2.7"
matrix:
  include:
    - python: 3.5
      env:
      - TOX_ENV=py35
    - python: 3.4
      env:
      - TOX_ENV=py34
env:
    - TOX_ENV=flake8
    - TOX_ENV=py27
    - TOX_ENV=py26
install:
    - pip install tox
    - sudo pip install tox
    - pip install codecov
    - coverage combine
script:
    - tox -e $TOX_ENV
    - sudo tox -e deploy
after_success:
  - codecov
